modLoader="javafml"
loaderVersion="[44,)"
license="MIT"
issueTrackerURL="https://github.com/TheLMiffy1111/PackagedExCrafting/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/packagedexcrafting"
authors="TheLMiffy1111"
[[mods]]
modId="packagedexcrafting"
version="${file.jarVersion}"
displayName="PackagedExCrafting"
description="A PackagedAuto addon that adds ExtendedCrafting autocrafting."

[[dependencies.packagedexcrafting]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.packagedexcrafting]]
    modId="extendedcrafting"
    mandatory=true
    versionRange="[5.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.packagedexcrafting]]
    modId="packagedauto"
    mandatory=true
    versionRange="[3.3.2,)"
    ordering="NONE"
    side="BOTH"
