modLoader = "javafml"
loaderVersion = "[46,)"
license = "MIT"
issueTrackerURL = "https://github.com/TheLMiffy1111/PackagedExCrafting/issues"

[[mods]]
	modId = "packagedexcrafting"
	version = "0@VERSION@"
	displayName = "PackagedExCrafting"
	description = "A PackagedAuto addon that adds ExtendedCrafting autocrafting."
	logoFile = "packagedexcrafting.logo.png"
	authors = "TheLMiffy1111"
	displayURL = "https://www.curseforge.com/minecraft/mc-mods/packagedexcrafting"

[[dependencies.packagedexcrafting]]
	modId = "forge"
	versionRange = "[46,)"
	mandatory = true

[[dependencies.packagedexcrafting]]
	modId = "packagedauto"
	versionRange = "[3.4.3,)"
	mandatory = true

[[dependencies.packagedexcrafting]]
	modId = "extendedcrafting"
	versionRange = "[6,)"
	mandatory = true
